#!/usr/bin/env node
'use strict';

const Targets = require('../..');

/**
 * The most basic possible target is simply a named function.
 */
function foo() {
    return "bar";
}

/**
 * A more complete target should may return a promise, has a label property and
 * a may have a prompts property which contains `inquirer` prompts for the target.
 */
function greet({ name }) {
    return `Hello, ${name}!`;
}
greet.label = "greet example";
greet.prompts = [
    {
        name: "name",
        message: "What's your name?",
        default: "World"
    }
];

/**
 * targets can return values, Promises or streams. here's a target which returns a stream
 */
function whoami() {
    return require('child_process').spawn('whoami');
}

/**
 * Register targets
 */
Targets({
    targets: {
        greet,
        foo,
        whoami
    }
});
